name: Build and Push to Existing or New Branch
on:
  push:
    branches:
      - sync_web


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Setup Node.js
    #  uses: actions/setup-node@v2
    #  with:
    #    node-version: '14'

    #- name: Install Dependencies
    #  run: npm install
    #
    #- name: Build
    #  run: npm run build

    #- name: Remove node_modules
    #  run: rm -rf node_modules

    - name: Copy index.html to cnvpytor.html
      run: |
        cp examples/cnvpytor/index.html cnvpytor.html
        cp examples/cnvpytor/cnvpytorTrackVCF.html .
        cp examples/cnvpytor/cnvpytorTrack.html .

    - name: Check if Branch Exists and commit changes
      run: |
        BRANCH_NAME="web_page"
        existed_in_remote=$(git ls-remote --heads origin ${BRANCH_NAME})

        if [[ -z ${existed_in_remote} ]]; then
          BRANCH_EXISTS=true
        else
          BRANCH_EXISTS=false
        fi
        echo "BRANCH_NAME: ${BRANCH_NAME}"
        echo "Branch exists: $BRANCH_EXISTS"

        git config --global user.name "arpanda"
        git config --global user.email "rjit17@gmail.com"
        git add .
        git commit -m "build web page"
        
        if [ "$BRANCH_EXISTS" = true ]; then
          git push origin "$BRANCH_NAME"
        else
          git checkout -b "$BRANCH_NAME"
          git push --set-upstream origin "$BRANCH_NAME"
        fi
