name: Build and Push to Existing or New Branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # You can adjust the Node.js version as needed

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Remove node_modules
      run: rm -rf node_modules

    - name: Copy index.html to cnvpytor.html
      run: cp examples/cnvpytor/index.html cnvpytor.html

    - name: Check if Branch Exists
      run: |
        BRANCH_NAME="web_page"
        if git rev-parse --verify "$BRANCH_NAME" >/dev/null 2>&1; then
          BRANCH_EXISTS=true
        else
          BRANCH_EXISTS=false
        fi
        echo "BRANCH_NAME: ${BRANCH_NAME}"
        echo "Branch exists: $BRANCH_EXISTS"
    - name: Debug
      run: |
        echo "BRANCH_NAME: $BRANCH_NAME"
        
    - name: Commit and Push Changes
      run: |
        git config --global user.name "arpanda"
        git config --global user.email "rjit17@gmail.com"
        git add .
        git commit -m "build web page"
        
        if [ "$BRANCH_EXISTS" = true ]; then
          git push origin "$BRANCH_NAME"
        else
          git checkout -b "$BRANCH_NAME"
          git push --set-upstream origin "$BRANCH_NAME"
        fi
