name: Build and Push to Existing or New Branch
on:
  push:
    branches:
      - sync_web

env:
  BRANCH_NAME: web_page

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if Branch Exists
      id: check_branch
      run: |
        if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
          BRANCH_EXISTS=true
        else
          BRANCH_EXISTS=false
        fi
        echo "Branch exists: $BRANCH_EXISTS"
        echo "::set-output name=branch_exists::$BRANCH_EXISTS"

    - name: Pull Changes if Branch Exists
      if: steps.check_branch.outputs.branch_exists == 'true'
      run: |
        git fetch origin "$BRANCH_NAME"
        git checkout "$BRANCH_NAME"
        git merge origin/"$BRANCH_NAME"

    - name: Copy index.html to cnvpytor.html
      run: |
        cp examples/cnvpytor/index.html cnvpytor.html
        cp examples/cnvpytor/cnvpytorTrackVCF.html .
        cp examples/cnvpytor/cnvpytorTrack.html .

    - name: commit changes if Branch Exists
      if: steps.check_branch.outputs.branch_exists == 'true'
      run: |
        git push origin "$BRANCH_NAME"

    - name: commit changes if Branch does not Exist
      if: steps.check_branch.outputs.branch_exists == 'false'
      run: |
        git checkout -b "$BRANCH_NAME"
        git push --set-upstream origin "$BRANCH_NAME"
